"""Add calendar_start_day field in companies table

Revision ID: 0c8a1948945c
Revises: 24a24b583195
Create Date: 2026-03-02 13:14:30.494848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8a1948945c'
down_revision: Union[str, Sequence[str], None] = '24a24b583195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('calendar_start_day', sa.String(), nullable=True))
    op.alter_column('companies', 'is_subscription_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'item_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'line_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoice_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_account_id'), table_name='invoices')
    op.drop_constraint(op.f('uq_invoices_invoice_id'), 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=True)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_account_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_account_id'), 'payments', ['account_id'], unique=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'PHP'::character varying"),
               existing_nullable=False)
    op.alter_column('payments', 'payment_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_id'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_id'), 'invoices', ['invoice_id'], unique=False)
    op.create_unique_constraint(op.f('uq_invoices_invoice_id'), 'invoices', ['invoice_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_invoices_account_id'), 'invoices', ['account_id'], unique=False)
    op.alter_column('invoices', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'PHP'::character varying"),
               existing_nullable=False)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoices', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoices', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoices', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Draft'::character varying"),
               existing_nullable=False)
    op.alter_column('invoices', 'invoice_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.alter_column('invoice_items', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('invoice_items', 'line_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoice_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoice_items', 'discount_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoice_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('invoice_items', 'quantity',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('invoice_items', 'item_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'Product'::character varying"),
               existing_nullable=False)
    op.alter_column('companies', 'is_subscription_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('companies', 'calendar_start_day')
    # ### end Alembic commands ###
