"""modify MEDIUM to NORMAL in priority in task table

Revision ID: 189571bcadb8
Revises: 200de2cffb04
Create Date: 2025-12-15 10:35:04.902506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '189571bcadb8'
down_revision: Union[str, Sequence[str], None] = '200de2cffb04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
