"""add_created_by_to_territories

Revision ID: 1de2ad0a96f1
Revises: 202602161430
Create Date: 2026-02-19 14:10:51.363307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de2ad0a96f1'
down_revision: Union[str, Sequence[str], None] = '202602161430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targets', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.add_column('territories', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'territories', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'territories', type_='foreignkey')
    op.drop_column('territories', 'created_by')
    op.alter_column('targets', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Active'::character varying"),
               existing_nullable=True)
    # ### end Alembic commands ###
