"""modify MEDIUM to NORMAL in priority in task table

Revision ID: 200de2cffb04
Revises: 124804810d37
Create Date: 2025-12-15 10:18:26.994873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200de2cffb04'
down_revision: Union[str, Sequence[str], None] = '124804810d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
