"""add account_territory association table for multi-territory support

Revision ID: 202602121000
Revises: da12151d5800
Create Date: 2026-02-12 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202602121000'
down_revision: Union[str, Sequence[str], None] = 'da12151d5800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create account_territory many-to-many association table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'account_territory',
        sa.Column('account_id', sa.Integer(), nullable=False),
        sa.Column('territory_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('account_id', 'territory_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - drop account_territory table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_territory')
    # ### end Alembic commands ###
