"""add created_by and status fields to targets table

Revision ID: 202602161430
Revises: 202602121000
Create Date: 2026-02-16 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202602161430'
down_revision: Union[str, Sequence[str], None] = '6c4a9a0f6a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - add created_by and status columns to targets table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('targets', sa.Column('status', sa.String(), nullable=True, server_default='Active'))
    
    op.create_foreign_key('fk_targets_created_by_users', 'targets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_targets_created_by'), 'targets', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - remove created_by and status columns from targets table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_targets_created_by'), table_name='targets')
    op.drop_constraint('fk_targets_created_by_users', 'targets', type_='foreignkey')
    op.drop_column('targets', 'status')
    op.drop_column('targets', 'created_by')
    # ### end Alembic commands ###
