"""add_tax_rate_to_companies_table

Revision ID: 288eaf94bf7e
Revises: e8f5a7b2c1d3
Create Date: 2026-02-06 08:51:37.780691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288eaf94bf7e'
down_revision: Union[str, Sequence[str], None] = 'e8f5a7b2c1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'tax_rate')
    # ### end Alembic commands ###
