"""fix comment-auth relationship

Revision ID: 3df4efd2ae94
Revises: e3fa586ca8a1
Create Date: 2026-01-26 14:02:52.969183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3df4efd2ae94'
down_revision: Union[str, Sequence[str], None] = 'e3fa586ca8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
