"""Add manager_id and user_id to territories

Revision ID: 488cc28f0ba9
Revises: 5d6edfac4abc
Create Date: 2025-12-16 14:09:58.299821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488cc28f0ba9'
down_revision: Union[str, Sequence[str], None] = '5d6edfac4abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
