"""Add trials fields in subscriptions

Revision ID: 5106360dd473
Revises: b2c3d4e5f7a8
Create Date: 2026-04-06 14:21:09.213709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5106360dd473'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'subscriptions',
        sa.Column('is_trial', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.add_column('subscriptions', sa.Column('trial_notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subscriptions', sa.Column('downgraded_to_free_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('subscriptions', 'is_trial', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'downgraded_to_free_at')
    op.drop_column('subscriptions', 'trial_notification_sent_at')
    op.drop_column('subscriptions', 'is_trial')
    # ### end Alembic commands ###
