"""add quoteitems table

Revision ID: 52e998160533
Revises: add_status_to_contacts
Create Date: 2026-01-27 14:50:28.046323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e998160533'
down_revision: Union[str, Sequence[str], None] = 'add_status_to_contacts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('quotes', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotes', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotes', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotes', 'discount_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotes', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('quotes', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('targets', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('targets', 'period_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'CUSTOM'::character varying"),
               existing_nullable=False)
    op.alter_column('quotes', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'PHP'::character varying"),
               existing_nullable=False)
    op.alter_column('quotes', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('quotes', 'discount_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('quotes', 'tax_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('quotes', 'tax_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('quotes', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.drop_column('contacts', 'status')
    # ### end Alembic commands ###
