"""modify territory table to accept multiple users in the same territory name

Revision ID: 5d6edfac4abc
Revises: 166544f69962
Create Date: 2025-12-16 14:00:07.994293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6edfac4abc'
down_revision: Union[str, Sequence[str], None] = '166544f69962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
