"""add currency and quota_period in companies table

Revision ID: 66beffc51650
Revises: 89abaa927472
Create Date: 2026-01-24 15:01:18.258640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66beffc51650'
down_revision: Union[str, Sequence[str], None] = '89abaa927472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('quota_period', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'quota_period')
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###
