"""Modify territory. Add assigned user and manager to the territory

Revision ID: 6cd09cac8b64
Revises: e8d10b44c7eb
Create Date: 2025-12-16 10:59:34.028416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cd09cac8b64'
down_revision: Union[str, Sequence[str], None] = 'e8d10b44c7eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
