"""update alembic/env.py

Revision ID: 78c96f630b9c
Revises: 5ef96a9fae63
Create Date: 2025-12-17 10:40:47.203612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78c96f630b9c'
down_revision: Union[str, Sequence[str], None] = '5ef96a9fae63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('deal_id', sa.Integer(), nullable=True))
    op.add_column('quotes', sa.Column('validity_days', sa.Integer(), nullable=True))
    op.alter_column('quotes', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_quotes_deal_name'), table_name='quotes')
    op.drop_constraint(op.f('quotes_account_id_fkey'), 'quotes', type_='foreignkey')
    op.create_foreign_key(None, 'quotes', 'deals', ['deal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quotes', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('quotes', 'deal_name')
    op.drop_column('quotes', 'amount')
    op.drop_column('quotes', 'validity_date')
    op.add_column('targets', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('targets', sa.Column('end_date', sa.Date(), nullable=False))
    op.alter_column('targets', 'target_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.alter_column('targets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_targets_end_date'), 'targets', ['end_date'], unique=False)
    op.create_index(op.f('ix_targets_start_date'), 'targets', ['start_date'], unique=False)
    op.create_index(op.f('ix_targets_user_id'), 'targets', ['user_id'], unique=False)
    op.drop_constraint(op.f('targets_created_by_fkey'), 'targets', type_='foreignkey')
    op.drop_column('targets', 'achieved')
    op.drop_column('targets', 'period')
    op.drop_column('targets', 'created_by')
    op.drop_column('targets', 'status')
    op.alter_column('tasks', 'priority',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               type_=sa.Enum('LOW', 'NORMAL', 'HIGH', name='prioritycategory'),
               nullable=True,
               postgresql_using="CASE WHEN priority::text = 'MEDIUM' THEN 'NORMAL'::prioritycategory ELSE priority::text::prioritycategory END")
    op.alter_column('tasks', 'status',
               existing_type=postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               type_=sa.Enum('IN_PROGRESS', 'COMPLETED', 'DEFERRED', 'NOT_STARTED', name='statuscategory'),
               nullable=True,
               postgresql_using="CASE WHEN status::text = 'TODO' THEN 'NOT_STARTED'::statuscategory ELSE status::text::statuscategory END")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('IN_PROGRESS', 'COMPLETED', 'DEFERRED', 'NOT_STARTED', name='statuscategory'),
               type_=postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               nullable=False)
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'NORMAL', 'HIGH', name='prioritycategory'),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='taskpriority'),
               nullable=False)
    op.add_column('targets', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('targets', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('targets', sa.Column('period', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('targets', sa.Column('achieved', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('targets_created_by_fkey'), 'targets', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_targets_user_id'), table_name='targets')
    op.drop_index(op.f('ix_targets_start_date'), table_name='targets')
    op.drop_index(op.f('ix_targets_end_date'), table_name='targets')
    op.alter_column('targets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('targets', 'target_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('targets', 'end_date')
    op.drop_column('targets', 'start_date')
    op.add_column('quotes', sa.Column('validity_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('quotes', sa.Column('deal_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.create_foreign_key(op.f('quotes_account_id_fkey'), 'quotes', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_quotes_deal_name'), 'quotes', ['deal_name'], unique=False)
    op.alter_column('quotes', 'total_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.drop_column('quotes', 'validity_days')
    op.drop_column('quotes', 'deal_id')
    # ### end Alembic commands ###
