"""add parent_company field in accounts table

Revision ID: 89abaa927472
Revises: 31d35329483f
Create Date: 2026-01-16 08:50:41.857757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89abaa927472'
down_revision: Union[str, Sequence[str], None] = '31d35329483f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('parent_company', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'parent_company')
    # ### end Alembic commands ###
