"""alembic test-1

Revision ID: a10121e72835
Revises: b67c2472b612
Create Date: 2026-02-21 16:40:22.956003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10121e72835'
down_revision: Union[str, Sequence[str], None] = 'b67c2472b612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'eme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eme', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
