"""add related_to_quote column in tasks, calls, and meetings table

Revision ID: c289ada03dee
Revises: f62f6b860e85
Create Date: 2026-01-30 15:22:50.476108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c289ada03dee'
down_revision: Union[str, Sequence[str], None] = 'f62f6b860e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('related_to_quote', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calls', 'quotes', ['related_to_quote'], ['id'], ondelete='CASCADE')
    op.add_column('meetings', sa.Column('related_to_quote', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meetings', 'quotes', ['related_to_quote'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('related_to_quote', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'quotes', ['related_to_quote'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'related_to_quote')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'related_to_quote')
    op.drop_constraint(None, 'calls', type_='foreignkey')
    op.drop_column('calls', 'related_to_quote')
    # ### end Alembic commands ###
