"""add is_private column in comments table

Revision ID: c4149b220f9f
Revises: 3df4efd2ae94
Create Date: 2026-01-26 14:26:05.828176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4149b220f9f'
down_revision: Union[str, Sequence[str], None] = '3df4efd2ae94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'is_private')
    # ### end Alembic commands ###
