"""add status in some tables

Revision ID: f62f6b860e85
Revises: a9c3268d6633
Create Date: 2026-01-30 09:58:36.904007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62f6b860e85'
down_revision: Union[str, Sequence[str], None] = 'a9c3268d6633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('territories', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('territories', 'status')
    op.drop_column('deals', 'status')
    # ### end Alembic commands ###
